name: heated_rivalry
channels:
  - conda-forge
dependencies:
  # These packages are required if you want your environment to show up in jupyterlab
  - python=3.11
  - ipywidgets
  - ipykernel
  # Commonly used packages
  - xarray
  - numpy=1.26.4
  - scipy
  - pandas
  - matplotlib
  - xrft
  - cartopy
  - glidertools
  - xhistogram
  - pip 
  - imageio 
  - scikit-learn
  - xgboost
  - pytorch
  - geopandas
  - pip:
    - tensorflow-macos
    - tensorflow-metal
    - graphviz
    - ml_dtypes==0.3.2
    - streamlit
    - streamlit-folium
    - folium
    - branca
    - geopandas